[global]
excludes = ["flake.lock", "*.sops.*", "justfile"]

[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.taplo]
command = "taplo"
includes = ["*.toml"]
options = ["format"]

[formatter.yaml]
command = "yamlfmt"
includes = ["*.yaml", "*.yml"]
